INSERT INTO library.publisher (Publisher_ID, Name) VALUES (1, 'Mariner Books');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (2, 'Houghton Mifflin Harcourt');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (3, 'Educa Books');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (4, 'BLOOMSBURY');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (5, 'Scholastic Press');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (6, 'Arthur A. Levine Books');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (7, 'Salamandra Bolsillo');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (8, 'Arthur');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (9, 'Prestige Kids');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (10, 'Bianka Diana Gales');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (11, 'Pandora-M');
INSERT INTO library.publisher (Publisher_ID, Name) VALUES (12, 'Curtea Veche');